{% set name = "nexus" %}
{% set version = "4.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nexusformat/code/archive/v{{ version }}.tar.gz
  sha256: e78a116feb2ebd04de31a8d8707c65e8e15a64aa8999a40fea305e3909bd6533
  patches:
    - include_libxml_sax.patch
    - nexus_windows.patch  # [win]

build:
  number: 5

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=2.8.8
    - ninja
  host:
    - hdf5
    - hdf4
    - jpeg
    - zlib
    - libxml2  # [not win]
    - ncurses  # [not win]
    - readline  # [not win]
  run:
    - hdf5
    - hdf4
    - ncurses  # [not win]

test:
  commands:
    - nxdir --help  # [not win]
    - nxtraverse -h  # [not win]
    - nxsummary --help  # [not win]
    - nxtranslate --help  # [not win]
    - if not exist %LIBRARY_LIB%\\NeXusCPP.lib exit 1  # [win]

about:
  home: https://github.com/nexusformat/code
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: NeXus is a common data format for neutron, x-ray, and muon science
  description: |
    NeXus is a common data format for neutron, x-ray, and muon science.
    It is being developed as an international standard by scientists and
    programmers representing major scientific facilities in order to facilitate
    greater cooperation in the analysis and visualization of neutron, x-ray, and muon data.
  doc_url: https://www.nexusformat.org
  dev_url: https://github.com/nexusformat/code

extra:
  recipe-maintainers:
    - beenje
